logging:
  level:
    tech:
      jhipster:
        pulsarapp: INFO
spring:
  application:
    name: Pulsarapp
  jackson:
    default-property-inclusion: non_absent
server:
  port: 8081
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
pulsar:
  client:
    service-url: pulsar://localhost:6650
